import Logo from "@/components/Logo";

export const dynamic = "force-static";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-neutral-200 px-4 py-4 sm:px-8">
        <Logo />
      </header>

      <main className="mx-auto max-w-3xl px-4 py-12 text-sm leading-6 text-neutral-700 sm:px-8">
        <h1 className="mb-2 text-2xl font-bold text-neutral-900">Terms of Use / End-User License Agreement</h1>
        <p className="mb-8 text-xs text-neutral-400">Last updated: September 20, 2026</p>

        <p className="mb-6">
          These Terms of Use (&quot;Terms&quot;) govern access to and use of Mama&apos;s Cleaning Crew&apos;s internal
          Owner&apos;s Dashboard application (&quot;the App&quot;). The App is an internal business-management tool used
          by Mama&apos;s Cleaning Crew and its employees — it is not offered to the general public, and accounts are
          created by invitation only.
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">1. Acceptance of terms</h2>
        <p className="mb-6">
          By logging into or otherwise using the App, you agree to these Terms. If you do not agree, do not use the
          App.
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">2. Accounts and access</h2>
        <p className="mb-6">
          Accounts are created by a Mama&apos;s Cleaning Crew administrator and are intended for use only by the
          individual they were issued to. You are responsible for keeping your login credentials confidential and for
          all activity that occurs under your account.
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">3. Acceptable use</h2>
        <p className="mb-4">You agree to use the App only for legitimate Mama&apos;s Cleaning Crew business purposes, and not to:</p>
        <ul className="mb-6 list-disc space-y-1 pl-5">
          <li>Access or attempt to access data or accounts you are not authorized to view.</li>
          <li>Use the App to store or transmit unlawful content.</li>
          <li>Attempt to interfere with or disrupt the App&apos;s normal operation.</li>
        </ul>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">4. Data ownership</h2>
        <p className="mb-6">
          All business data entered into or generated by the App (training records, HR records, financial data,
          leads, and applicant information) is owned by Mama&apos;s Cleaning Crew.
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">5. Third-party integrations</h2>
        <p className="mb-6">
          The App may connect to third-party services, including QuickBooks Online, at the direction of an authorized
          administrator. Connecting a third-party service authorizes the App to access only the specific data
          described at the time of connection (see our{" "}
          <a href="/legal/privacy-policy" className="text-brand-700 underline">
            Privacy Policy
          </a>{" "}
          for details), solely to support internal business reporting. Use of any third-party service is also
          subject to that service&apos;s own terms (e.g., Intuit&apos;s QuickBooks terms of service).
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">6. No warranty</h2>
        <p className="mb-6">
          The App is provided &quot;as is,&quot; without warranties of any kind, express or implied. We do not guarantee
          the App will be uninterrupted, error-free, or fit for any particular purpose beyond its intended internal
          business use.
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">7. Limitation of liability</h2>
        <p className="mb-6">
          To the fullest extent permitted by law, Mama&apos;s Cleaning Crew is not liable for any indirect,
          incidental, or consequential damages arising from use of the App.
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">8. Termination</h2>
        <p className="mb-6">
          We may suspend or terminate your access to the App at any time, including upon separation from employment
          with Mama&apos;s Cleaning Crew.
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">9. Changes to these terms</h2>
        <p className="mb-6">
          We may update these Terms from time to time. The &quot;last updated&quot; date at the top of this page
          reflects the most recent revision.
        </p>

        <h2 className="mb-2 mt-8 text-base font-semibold text-neutral-900">10. Contact us</h2>
        <p className="mb-6">
          Questions about these Terms can be sent to{" "}
          <a href="mailto:shar@mamascleaningcrew.com" className="text-brand-700 underline">
            shar@mamascleaningcrew.com
          </a>
          .
        </p>
      </main>
    </div>
  );
}
